In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
from time import time
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [80]:
# Loading pre-processed data / Creating training and test data sets

In [81]:
data = pd.read_csv('cleaned_data.csv') # load cleaned data

In [82]:
data

review sentiment  \
0      one reviewers mentioned watching oz episode ho...  positive   
1      wonderful little production filming technique ...  positive   
2      thought wonderful way spend time hot summer we...  positive   
3      basically family little boy jake thinks zombie...  negative   
4      petter mattei love time money visually stunnin...  positive   
...                                                  ...       ...   
49577  thought movie right good job creative original...  positive   
49578  bad plot bad dialogue bad acting idiotic direc...  negative   
49579  catholic taught parochial elementary schools n...  negative   
49580  going disagree previous comment side maltin on...  negative   
49581  one expects star trek movies high art fans exp...  negative   

                                           lemmatization  \
0      one reviewer mentioned watching oz episode hoo...   
1      wonderful little production filming technique ...   
2      thought wonderful way spend time hot summer we...   
3      basically family little boy jake think zombie ...   
4      petter mattei love time money visually stunnin...   
...                                                  ...   
49577  thought movie right good job creative original...   
49578  bad plot bad dialogue bad acting idiotic direc...   
49579  catholic taught parochial elementary school nu...   
49580  going disagree previous comment side maltin on...   
49581  one expects star trek movie high art fan expec...   

                                                stemming  
0      one review mention watch oz episod hook right ...  
1      wonder littl product film techniqu unassum old...  
2      thought wonder way spend time hot summer weeke...  
3      basic famili littl boy jake think zombi closet...  
4      petter mattei love time money visual stun film...  
...                                                  ...  
49577  thought movi right good job creativ origin fir...  
49578  bad plot bad dialogu bad act idiot direct anno...  
49579  cathol taught parochi elementari school nun ta...  
49580  go disagre previou comment side maltin one sec...  
49581  one expect star trek movi high art fan expect ...  

[49582 rows x 4 columns]

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['lemmatization'], data["sentiment"], train_size = 0.75)


In [89]:
tf_vectorizer = TfidfVectorizer(stop_words='english') # create Object of class TfidfVectorizer

X_train_tf = tf_vectorizer.fit_transform(X_train) # run method fit_transform on training set

print("n_samples: %d, n_features: %d" % X_train_tf.shape)
 

n_samples: 44623, n_features: 87630


In [90]:
X_train_tf

<44623x87630 sparse matrix of type '<class 'numpy.float64'>'
	with 3690014 stored elements in Compressed Sparse Row format>

In [91]:
naive_bayes_classifier = MultinomialNB() # create object naive_bayes_classifier
naive_bayes_classifier.fit(X_train_tf, y_train) # run method fit from the class MultinomialNB

 
 

n_samples: 44623, n_features: 87630


In [92]:
# predict the new document from the testing dataset
X_test_tf = tf_vectorizer.transform(X_test) # Create a Vector TF from test data 
y_pred = naive_bayes_classifier.predict(X_test_tf)
 
# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred,
                                            target_names=['Positive', 'Negative']))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

print('------------------------------')


accuracy:   0.853
              precision    recall  f1-score   support

    Positive       0.85      0.86      0.85      2453
    Negative       0.86      0.85      0.85      2506

    accuracy                           0.85      4959
   macro avg       0.85      0.85      0.85      4959
weighted avg       0.85      0.85      0.85      4959

confusion matrix:
[[2099  354]
 [ 373 2133]]
------------------------------


In [65]:
#Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [66]:
tf_vectorizer = CountVectorizer() # or term frequency
X_train_tf = tf_vectorizer.fit_transform(X_train)

In [67]:
 
X_test_tf = tf_vectorizer.transform(X_test)
print("n_samples: %d, n_features: %d" % X_train_tf.shape)
 

n_samples: 37186, n_features: 63025


In [68]:
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train_tf,y_train)

MultinomialNB()

In [69]:
y_pred = naive_bayes_classifier.predict(X_test_tf)

 
X_test_tf = tf_vectorizer.transform(X_test) # Create a Vector TF from test data 
y_pred = naive_bayes_classifier.predict(X_test_tf)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred,
                                            target_names=['Positive', 'Negative']))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

print('------------------------------')

accuracy:   0.854
              precision    recall  f1-score   support

    Positive       0.84      0.87      0.86      6129
    Negative       0.87      0.83      0.85      6267

    accuracy                           0.85     12396
   macro avg       0.85      0.85      0.85     12396
weighted avg       0.85      0.85      0.85     12396

confusion matrix:
[[5356  773]
 [1041 5226]]
------------------------------


In [70]:
## I will look at it later 

In [77]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=20000)
neigh.fit(X_train_tf, y_train)
 

KNeighborsClassifier(n_neighbors=20000)

In [78]:
# predict the new document from the testing dataset
from sklearn.metrics import plot_confusion_matrix    
    
y_pred = neigh.predict(X_test_tf)
 
# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred,
                                            target_names=['Positive', 'Negative']))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

print('------------------------------')


accuracy:   0.524
              precision    recall  f1-score   support

    Positive       0.51      1.00      0.67      6129
    Negative       0.96      0.06      0.11      6267

    accuracy                           0.52     12396
   macro avg       0.73      0.53      0.39     12396
weighted avg       0.74      0.52      0.39     12396

confusion matrix:
[[6113   16]
 [5884  383]]
------------------------------


In [29]:
#from sklearn.metrics import plot_confusion_matrix
#plot_confusion_matrix(y_pred, X_test_tf.toarray(), y_test, display_labels=["positive","negative"], cmap=plt.cm.Blues)
#leider zu groß

MemoryError: Unable to allocate 13.3 GiB for an array with shape (12500, 143107) and data type float64